[env]
_.file = { path = ".env" }

[tools]
rust = { version = "stable", postinstall = "mise exec -- rustup component add clippy rustfmt rust-analyzer" }
lefthook = "latest"

[hooks.postinstall]
run = "lefthook install"
